# Generated by Django 4.2.3 on 2024-03-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=200, null=True)),
                ('nom', models.CharField(max_length=200, null=True)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('adresse', models.TextField()),
                ('ville', models.CharField(max_length=200, unique=True)),
                ('numero_telephone', models.CharField(max_length=9)),
                ('livre', models.BooleanField(default=False)),
            ],
        ),
    ]
