# Generated by Django 4.2.3 on 2023-11-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=200, unique=True)),
                ('nom', models.CharField(max_length=200, null=True)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('adresse', models.CharField(max_length=200, unique=True)),
                ('Ville', models.CharField(max_length=200, unique=True)),
                ('zipcode', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['date_commande'],
            },
        ),
    ]
