# Generated by Django 4.2.3 on 2024-03-31 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='code_pays',
            field=models.CharField(choices=[('+1', '+1 - USA'), ('+44', '+221 - SN'), ('+33', '+33 - France')], default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commande',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='commande',
            name='adresse',
            field=models.CharField(max_length=200),
        ),
    ]
