# Generated by Django 4.2.3 on 2024-03-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0002_alter_commande_prenom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commande',
            options={},
        ),
        migrations.RenameField(
            model_name='commande',
            old_name='Ville',
            new_name='ville',
        ),
        migrations.AlterField(
            model_name='commande',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
