# Generated by Django 4.2.3 on 2024-03-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0003_alter_commande_options_rename_ville_commande_ville_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='total',
        ),
        migrations.AddField(
            model_name='commande',
            name='livre',
            field=models.BooleanField(default=False),
        ),
    ]
