# Generated by Django 4.2.3 on 2023-09-19 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='subtotal',
        ),
    ]
