# Generated by Django 4.2.3 on 2023-09-21 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0003_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='subtotal',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
