# Generated by Django 4.2.3 on 2023-09-21 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0004_cartitem_subtotal_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='subtotal',
        ),
    ]
