# Generated by Django 4.2.3 on 2024-04-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_alter_product_quantity_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='titre',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
